---

- name: delete old folder for display-controller
  file:
    path: /opt/display-controller
    state: absent

- name: download new controller version
  ansible.builtin.git:
    repo: https://github.com/ZoiosNET/ffw-ra-rauental-monitor.git
    dest: /opt/display-controller
    version: main
    clone: yes
    update: yes

- name: copy settings.propperties file
  template:
    src: templates/controller-settings.propperties.j2
    dest: /opt/display-controller/settings.propperties
    owner: root
    group: root
    mode: '0644'

- name: register display-controller service
  template:
    src: templates/display-controller.service.j2
    dest: /etc/systemd/system/display-controller.service
    owner: root
    group: root
    mode: '0755'

- name: enable and restart display-controller service
  service:
    name: display-controller.service
    enabled: yes
    daemon-reload: yes
    state: restarted
