---

- name: Install required software for kiosk
  apt:
    name:
    - xserver-xorg-video-all
    - xserver-xorg-input-all
    - xserver-xorg-core 
    - xinit
    - x11-xserver-utils
    - unclutter
    state: present
    install_recommends: no

- name: Install required software for chromium
  apt:
    name:
    - chromium-browser
    - libasound2
    state: present
    install_recommends: yes

- name: create tmp dir for 112-display
  file:
    path: /tmp/112-display
    state: directory
    owner: pi
    group: pi
    mode: '0755'

- name: unzip display-software arm64
  unarchive:
    src: files/112-display-linux-arm64.zip
    dest: /tmp/112-display
    owner: pi
    group: pi
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: copy display-software arm64
  copy:
    src: /tmp/112-display/112-display-linux-arm64/
    dest: /home/pi/112-display
    owner: pi
    group: pi
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: unzip display-software armv7l
  unarchive:
    src: files/112-display-linux-armv7l.zip
    dest: /tmp/112-display
    owner: pi
    group: pi
    mode: '0755'
  when: ansible_architecture == "armv7l"

- name: copy display-software armv7l
  copy:
    src: /tmp/112-display/112-display-linux-armv7l/
    dest: /home/pi/112-display
    owner: pi
    group: pi
    mode: '0755'
  when: ansible_architecture == "armv7l"

- name: create config dir
  file:
    path: /home/pi/config
    state: directory
    owner: pi
    group: pi
    mode: '0755'

- name: copy settings.json file
  template:
    src: templates/112-display-settings.json.j2
    dest: /home/pi/config/settings.json
    owner: pi
    group: pi
    mode: '0644'

- name: copy bash_profile file
  template:
    src: templates/bash_profile.j2
    dest: /home/pi/.bash_profile
    owner: pi
    group: pi
    mode: '0755'

- name: copy xinitrc file
  template:
    src: templates/xinitrc.j2
    dest: /home/pi/.xinitrc
    owner: pi
    group: pi
    mode: '0755'

- name: copy boot_config file
  template:
    src: templates/boot_config.txt.j2
    dest: /boot/config.txt
    owner: root
    group: root
    mode: '0755'
