---

- name: Install required kiosk software
  apt:
    name:
    - xserver-xorg-video-all
    - xserver-xorg-input-all
    - xserver-xorg-core 
    - xinit
    - x11-xserver-utils
    - chromium-browser
    - unclutter
    state: present
    install_recommends: no

- name: copy bash_profile file
  template:
    src: templates/bash_profile.j2
    dest: /home/pi/.bash_profile
    owner: pi
    group: pi
    mode: '0755'

- name: copy xinitrc file
  template:
    src: templates/xinitrc.j2
    dest: /home/pi/.xinitrc
    owner: pi
    group: pi
    mode: '0755'

- name: copy boot_config file
  template:
    src: templates/boot_config.txt.j2
    dest: /boot/config.txt
    owner: root
    group: root
    mode: '0755'
