---

- name: register watch-service command
  template:
    src: templates/watch-service.sh.j2
    dest: /bin/watch-service
    owner: root
    group: root
    mode: '0755'

- name: add minutly service check via cron
  ansible.builtin.cron:
    name: "minutly service check"
    job: "timeout 50 watch-service display-controller"
    state: present

- name: register telegram-ping command
  template:
    src: templates/telegram-ping.sh.j2
    dest: /bin/telegram-ping
    owner: root
    group: root
    mode: '0755'

- name: add hourly telegram-ping via cron
  ansible.builtin.cron:
    name: "hourly telegram-ping"
    job: "timeout 30 /bin/bash -c \"telegram-ping\""
    minute: "0"
    state: present