---

- name: dist-upgrade system
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: full-upgrade system
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: full

- name: Install required system software
  apt:
    name:
    - git
    - git-lfs
    - curl
    - unzip
    - python3
    - python3-requests
    - python3-serial
    - cec-utils
    state: present
