---

- name: Update system
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: full

- name: Install required system software
  apt:
    name:
    - git
    - curl
    - python3
    - python3-requests
    - cec-utils
    state: present
