---

- name: register update-service on boot
  template:
    src: templates/display-updater.service.j2
    dest: /etc/systemd/system/display-updater.service
    owner: root
    group: root
    mode: '0755'

- name: enable display-updater
  service:
    name: display-updater.service
    enabled: yes
    daemon-reload: yes

- name: add daily reboot via cron
  ansible.builtin.cron:
    name: "daily reboot"
    minute: "6"
    hour: "3"
    job: "/sbin/shutdown -r now"
    state: present

- name: add daily Xauthority removal via cron
  ansible.builtin.cron:
    name: "remove Xauthority to fix xinit"
    minute: "2"
    hour: "4"
    job: "rm /home/pi/.Xauthority"
    state: present

- name: add second daily reboot via cron for update
  ansible.builtin.cron:
    name: "daily reboot for update"
    minute: "6"
    hour: "4"
    job: "/sbin/shutdown -r now"
    state: present
