---

- name: register update-service on boot
  template:
    src: templates/display-updater.service.j2
    dest: /etc/systemd/system/display-updater.service
    owner: root
    group: root
    mode: '0755'

- name: enable display-updater
  service:
    name: display-updater.service
    enabled: yes
    daemon-reload: yes

- name: add daily reboot via cron
  ansible.builtin.cron:
    name: "daily reboot"
    minute: "6"
    hour: "3"
    job: "/sbin/shutdown -r now"
    state: present

- name: add second daily reboot via cron for update
  ansible.builtin.cron:
    name: "daily reboot for update"
    minute: "6"
    hour: "4"
    job: "/sbin/shutdown -r now"
    state: absent

- name: reboot for rpi-ra-rauental
  ansible.builtin.cron:
    name: "daily reboot rauental"
    minute: "1"
    hour: "4"
    job: "/sbin/shutdown -r now"
    state: present
  when: "{{lookup('file', '/etc/hostname')}}" == "rpi-ra-rauental"
  
- name: reboot for rpi-ra-plittersdorf
  ansible.builtin.cron:
    name: "daily reboot plittersdorf"
    minute: "31"
    hour: "4"
    job: "/sbin/shutdown -r now"
    state: present
  when: "{{lookup('file', '/etc/hostname')}}" == "rpi-ra-plittersdorf"
  
- name: reboot for rpi-ra-ottersdorf
  ansible.builtin.cron:
    name: "daily reboot ottersdorf"
    minute: "1"
    hour: "5"
    job: "/sbin/shutdown -r now"
    state: present
  when: "{{lookup('file', '/etc/hostname')}}" == "rpi-ra-ottersdorf"
  
- name: reboot for rpi-ra-wintersdorf
  ansible.builtin.cron:
    name: "daily reboot wintersdorf"
    minute: "31"
    hour: "5"
    job: "/sbin/shutdown -r now"
    state: present
  when: "{{lookup('file', '/etc/hostname')}}" == "rpi-ra-wintersdorf"

- name: reboot for rpi-ra-niederbuehl
  ansible.builtin.cron:
    name: "daily reboot niederbuehl"
    minute: "1"
    hour: "6"
    job: "/sbin/shutdown -r now"
    state: present
  when: "{{lookup('file', '/etc/hostname')}}" == "rpi-ra-niederbuehl"
