---

- name: register update-service on boot
  template:
    src: templates/display-updater.service.j2
    dest: /etc/systemd/system/display-updater.service
    owner: root
    group: root
    mode: '0755'

- name: enable display-updater
  service:
    name: display-updater.service
    enabled: yes
    daemon-reload: yes
